config/routes.rb
Rails.application.routes.draw do

	devise_for :users, controllers: { sessions: 'sessions' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  
  devise_scope :user do
      root to: 'sessions#new'
  end

  resources :dashboard, only: :index
  resources :locations do
  	collection do
  		post :search
  	end
    resources :share_locations, only: [:new, :create]
  end
  resources :share_locations, only: [:index, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ApplicationRecord

	belongs_to :user
	has_many :share_location, dependent: :destroy
end

app/models/share_location.rb
class ShareLocation < ApplicationRecord

	belongs_to :share_by, foreign_key: 'share_by_id', class_name: 'User'
	belongs_to :share_with, foreign_key: 'share_with_id', class_name: 'User', optional: true
	belongs_to :location

	scope :private_share, -> {where(is_private: true)}
  	scope :public_share, -> {where(is_private: false)}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable
  # , :registerable,:recoverable, :rememberable, :validatable

  has_many :locations
  has_many :shared_by_me, foreign_key: 'share_by_id', class_name: 'ShareLocation'
  has_many :shared_with_me, foreign_key: 'share_with_id', class_name: 'ShareLocation'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	def after_sign_in_path_for(resource)
	  dashboard_index_path # your path
	end

	def current_user
	   @current_user ||= super || User.find(@current_user_id)
	end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
	before_action :authenticate_user!, :current_user
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
	before_action :authenticate_user!, :current_user

	def index
		@locations = @current_user.locations
		@private_locations = @current_user.shared_with_me.try(:private_share).includes(:location)
		@public_locations = ShareLocation.includes(:location).where(is_private: false)
	end

	def search
		
	end

	def new
		@location  = Location.new
	end

	def create
		@location  = @current_user.locations.create!(location_params)
		redirect_to locations_path
	end


	def destroy
		@location  = @current_user.locations.find(params[:id])
		@location.destroy!
		redirect_to locations_path
	end

	def show
		@location  = @current_user.locations.find(params[:id])
	end

	def update
	end

	private

	def location_params
		params.require(:location).permit(:lat, :long, :address, :address_type)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
	layout 'auth'
	def create
		puts "Login......................................"
    	# custom sign-in code
    	super()
  	end
end

app/controllers/share_locations_controller.rb
class ShareLocationsController < ApplicationController

	before_action :authenticate_user!, :current_user

	def index
		@shared_locations = @current_user.shared_by_me.includes(:location)
	end

	def new
		@location = @current_user.locations.find(params[:location_id])
		@shared_location = ShareLocation.new()
	end

	def create
		@location = @current_user.locations.find(params[:location_id])
		if params[:share_location][:is_private] == "true"
			params[:share_location][:share_with_id].each do |user_id|
				if user_id.present?
					@shared_location = ShareLocation.create!({
						share_by_id: @current_user.id,
						share_with_id: user_id,
						location: @location,
						is_private: true
					})
				end
			end
		else
			@shared_location = ShareLocation.create!({
				share_by_id: @current_user.id,
				location: @location,
				is_private: false
			})
		end

		redirect_to share_locations_path
	end

	def destroy
		@shared_location = ShareLocation.find(params[:id])
		@shared_location.destroy!
		redirect_to share_locations_path
	end

end

app/helpers/active_link_to_helper.rb
module ActiveLinkToHelper
  def active_link_to(*args)
    if block_given?
      link_to args[0], *options_with_active_class(args, true) do
        yield
      end
    else
      link_to args[0], args[1], *options_with_active_class(args, false)
    end
  end

  def add_active_class(option)
    return 'active' if active_link?(option)
  end

  def active_link?(option)
    return current_page?(option) if option.is_a? String

    return nil unless option.is_a? Hash

    return current_page?(option[:path]) if option[:path]

    if option[:starting_with]
      return request.path.start_with? option[:starting_with]
    end

    if option[:includes]
      includes = [option[:includes]].flatten
      return includes.any? { |elem| request.path.include? elem }
    end
  end

  private

  def options_with_active_class(args, block)
    path = block ? args[0] : args[1]
    options_array = block ? args[1..-1] : args[2..-1]
    options = {}.merge(*options_array).symbolize_keys

    return options_array unless active_link?(options.merge({ path: path }))

    if options[:class].is_a? String
      options[:class] += ' active'
    else
      'active'
    end

    options.map {|k,v| {k => v}}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include ActiveLinkToHelper
  include TemplateNavHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/share_locations_helper.rb
module ShareLocationsHelper
end

app/helpers/template_nav_helper.rb
module TemplateNavHelper
  def nav_context(name, title, icon: '', active_link: false, &block)
    "<li class='nav-item #{'active' if active_link}'>
      <a class='nav-link #{'collapsed' unless active_link}'
        href='#' data-toggle='collapse' 
        data-target='##{name}'
        aria-expanded='true'
        aria-controls='#{name}'>
        <i class='fas fa-fw fa-#{icon}'></i>
        <span>#{title}</span>
      </a>
      <div id='#{name}'
        class='collapse #{'show' if active_link}'
        aria-labelledby='headingTwo'
        data-parent='#accordionSidebar'>
        <div class='bg-white py-2 collapse-inner rounded'>
          #{capture(&block)}
        </div>
      </div>
    </li>".html_safe
  end
end

app/views/dashboard/index.html.erb
<div class="d-sm-flex align-items-center justify-content-between mb-4">
  <h1 class="h3 mb-0 text-gray-800">Location Share Overview</h1>
</div>

<div class="row">

  <!-- My shared Location -->
  <div class="col-xl-3 col-md-6 mb-4">
    <div class="card border-left-primary shadow h-100 py-2">
      <div class="card-body">
        <div class="row no-gutters align-items-center">
          <div class="col mr-2">
            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">My Shared Location(Private)</div>
            <div class="h5 mb-0 font-weight-bold text-gray-800">10</div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Shared Location with me -->
  <div class="col-xl-3 col-md-6 mb-4">
    <div class="card border-left-success shadow h-100 py-2">
      <div class="card-body">
        <div class="row no-gutters align-items-center">
          <div class="col mr-2">
            <div class="text-xs font-weight-bold text-success text-uppercase mb-1">My Shared Location(Public)</div>
            <div class="h5 mb-0 font-weight-bold text-gray-800">50</div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Location Shared with me(Private) -->
  <div class="col-xl-3 col-md-6 mb-4">
    <div class="card border-left-info shadow h-100 py-2">
      <div class="card-body">
        <div class="row no-gutters align-items-center">
          <div class="col mr-2">
            <div class="text-xs font-weight-bold text-info text-uppercase mb-1">Location Shared With Me(Private)</div>
            <div class="row no-gutters align-items-center">
              <div class="col-auto">
                <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">50</div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Pending Requests Card Example -->
  <div class="col-xl-3 col-md-6 mb-4">
    <div class="card border-left-warning shadow h-100 py-2">
      <div class="card-body">
        <div class="row no-gutters align-items-center">
          <div class="col mr-2">
            <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">Location Shared With Me(Public)</div>
            <div class="h5 mb-0 font-weight-bold text-gray-800">18</div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Template</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body id="page-top">

    <div id="wrapper">
      <%= render  "layouts/shared/sidebar" %>

      <div id="content-wrapper" class="d-flex flex-column">

        <div id="content">
          <%= render "layouts/shared/topbar" %>

          <div class="container-fluid">
            <%= yield %>
          </div>
        </div>

        <footer class="sticky-footer bg-white">
          <div class="container my-auto">
            <div class="copyright text-center my-auto">
              <span>Copyright &copy; Your Website 2019</span>
            </div>
          </div>
        </footer>

      </div>

    </div>

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
      <i class="fas fa-angle-up"></i>
    </a>

    <%= render "layouts/shared/logout_modal" %>
  </body>
</html>

app/views/layouts/auth.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Template</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg-gradient-primary">
    <div class="container">

      <!-- Outer Row -->
      <div class="row justify-content-center">

        <div class="col-xl-10 col-lg-12 col-md-9">

          <div class="card o-hidden border-0 shadow-lg my-5">
            <div class="card-body p-0">
              <!-- Nested Row within Card Body -->
              <%= yield %>
            </div>
          </div>

        </div>

      </div>

    </div>
  </body>
</html>

app/views/layouts/shared/_logout_modal.html.erb
  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <!-- <a class="btn btn-primary" href="<%= destroy_user_session_path %>">Logout</a> -->
          <%= link_to "Logout", destroy_user_session_path, class: "btn btn-primary", method: :delete, :data => { :no_turbolink => true } %>
        </div>
      </div>
    </div>
  </div>

app/views/layouts/shared/_messages.html.erb
<li class="nav-item dropdown no-arrow mx-1">
  <a href="#" class="nav-link dropdown-toggle" id="messagesDropdown" 
    role="button" data-toggle="dropdown" aria-haspopup="true" 
    aria-expanded="false">
    <i class="fas fa-envelope fa-fw"></i>

    <!-- Counter - Messages -->
    <% if @messages.present? %>
      <span class="badge badge-danger badge-counter">
        <%= @messages.size %>
      </span>
    <% end %>
  </a>

  <!-- Dropdown - Messages -->
  <div aria-labelledby="messagesDropdown"
    class="dropdown-list dropdown-menu dropdown-menu-right
           shadow animated--grow-in">

    <h6 class="dropdown-header">
      Message Center
    </h6>

    <% @messages&.each do |message| %>
    <a class="dropdown-item d-flex align-items-center" href="#">
      <div class="dropdown-list-image mr-3">
        <img class="rounded-circle" src="<%= message.sender_avatar %>" alt="">
        <div class="status-indicator bg-success"></div>
      </div>
      <div class="font-weight-bold">
        <div class="text-truncate"><%= message.content %></div>
        <div class="small text-gray-500"><%= message.sender %></div>
      </div>
    </a>
    <% end %>

    <a class="dropdown-item text-center small text-gray-500" href="#">
      Read More Messages
    </a>
  </div>
</li>

app/views/layouts/shared/_notifications.html.erb
<li class="nav-item dropdown no-arrow mx-1">
  <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" 
    role="button" data-toggle="dropdown"aria-haspopup="true"
    aria-expanded="false">
    <i class="fas fa-bell fa-fw"></i>

    <!-- Counter - Alerts -->
    <% if @notifications.present? %>
      <span class="badge badge-danger badge-counter">
        <%= @notifications.size %>+
      </span>
    <% end %>
  </a>

  <!-- Dropdown - Alerts -->
  <div aria-labelledby="alertsDropdown"
    class="dropdown-list dropdown-menu dropdown-menu-right 
           shadow animated--grow-in">

    <h6 class="dropdown-header">
      Alerts Center
    </h6>

    <% @notifications&.each do |notification| %>
    <a class="dropdown-item d-flex align-items-center" href="#">
      <div class="mr-3">
        <div class="icon-circle bg-<%= notification.kind %>">
          <i class="fas fa-file-alt text-white"></i>
        </div>
      </div>
      <div>
        <div class="small text-gray-500"><%= notification.date %></div>
        <% if notification.viewed %>
          <%= notification.content %>
        <% else %>
          <span class="font-weight-bold"><%= notification.content %></span>
        <% end %>
      </div>
    </a>
    <% end %>

    <a class="dropdown-item text-center small text-gray-500" href="#">
      Show All Alerts
    </a>
  </div>
</li>

app/views/layouts/shared/_search_dropdown.html.erb
<li class="nav-item dropdown no-arrow d-sm-none">
  <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <i class="fas fa-search fa-fw"></i>
  </a>
  <!-- Dropdown - Messages -->
  <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
    <form class="form-inline mr-auto w-100 navbar-search">
      <%= render "layouts/shared/search_field" %>
    </form>
  </div>
</li>

app/views/layouts/shared/_search_field.html.erb
<div class="input-group">
  <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
  <div class="input-group-append">
    <button class="btn btn-primary" type="button">
      <i class="fas fa-search fa-sm"></i>
    </button>
  </div>
</div>

app/views/layouts/shared/_sidebar.html.erb
<!-- Sidebar -->
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

  <!-- Sidebar - Brand -->
  <a class="sidebar-brand d-flex align-items-center justify-content-center" href="<%= root_path %>">
    <div class="sidebar-brand-icon rotate-n-15">
      <i class="fas fa-laugh-wink"></i>
    </div>
    <div class="sidebar-brand-text mx-3">Location Sharing</div>
  </a>

  <!-- Divider -->
  <hr class="sidebar-divider my-0">

  <!-- Nav Item - Dashboard -->
  <li class="nav-item">
    <a class="nav-link" href="<%= root_path %>">
      <i class="fas fa-fw fa-tachometer-alt"></i>
      <span>Dashboard</span></a>
  </li>

  <!-- Divider -->
  <hr class="sidebar-divider">

  <!-- Heading -->
  <div class="sidebar-heading">
    Locations
  </div>

  <li class="nav-item <%= add_active_class(locations_path) %>">
    <a class="nav-link" href="<%= locations_path %>">
      <i class="fas fa-fw fa-chart-area"></i>
      <span>My Location</span>
    </a>
  </li>

  <li class="nav-item <%= add_active_class(share_locations_path) %>">
    <a class="nav-link" href="<%= share_locations_path %>">
      <i class="fas fa-fw fa-chart-area"></i>
      <span>Share Location</span>
    </a>
  </li>
</ul>
<!-- End of Sidebar -->

app/views/layouts/shared/_topbar.html.erb
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

  <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
    <i class="fa fa-bars"></i>
  </button>

  <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
    <%= render "layouts/shared/search_field" %>    
  </form>

  <ul class="navbar-nav ml-auto">
    <%= render "layouts/shared/search_dropdown" %>
    <%= render "layouts/shared/notifications" %>
    <%= render "layouts/shared/messages" %>

    <div class="topbar-divider d-none d-sm-block"></div>

    <%= render "layouts/shared/user_nav" %>
  </ul>

</nav>

app/views/layouts/shared/_user_nav.html.erb
<li class="nav-item dropdown no-arrow">
  <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <span class="mr-2 d-none d-lg-inline text-gray-600 small"><%= @current_user.name %></span>
    <img class="img-profile rounded-circle" src="https://source.unsplash.com/QAB-WJcbgJk/60x60">
  </a>
  <!-- Dropdown - User Information -->
  <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
    <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
      <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
      Logout
    </a>
  </div>
</li>

app/views/locations/index.html.erb
<!-- Page Heading -->
<h1 class="h3 mb-2 text-gray-800">My Locations</h1>
<!-- DataTales Example -->
<div class="card shadow mb-4">
  <div class="card-header py-3">
    <%= link_to "Add New Location", new_location_path, class: "btn btn-primary" %>
  </div>
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
        <thead>
          <tr>
            <th>Address Type</th>
            <th>Address</th>
            <th>Lat</th>
            <th>Long</th>
            <th>Action</th>
          </tr>
        </thead>
        <tfoot>
          <tr>
            <th>Address Type</th>
            <th>Address</th>
            <th>Lat</th>
            <th>Long</th>
            <th>Action</th>
          </tr>
        </tfoot>
        <tbody>
          <% @locations.each do |location| %>
            <tr>
              <th><%= location.address_type %></th>
              <th><%= location.address %></th>
              <th><%= location.lat %></th>
              <th><%= location.long %></th>
              <th>
               <%= link_to "Delete", location_path(location), class: "btn btn-danger", method: :delete, :data => { :no_turbolink => true } %>
               <%= link_to "Share", new_location_share_location_path(location.id), class: "btn btn-primary" %>
              </th>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<!-- Page Heading -->
<h1 class="h3 mb-2 text-gray-800">Locations Shared With Me (Private)</h1>
<!-- DataTales Example -->
<div class="card shadow mb-4">
  <div class="card-header py-3">
    <%#= link_to "Add New Location", new_location_path, class: "btn btn-primary" %>
  </div>
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
        <thead>
          <tr>
            <th>Address Type</th>
            <th>Address</th>
            <th>Lat</th>
            <th>Long</th>
          </tr>
        </thead>
        <tfoot>
          <tr>
            <th>Address Type</th>
            <th>Address</th>
            <th>Lat</th>
            <th>Long</th>
          </tr>
        </tfoot>
        <tbody>
          <% @private_locations.each do |private_shared_location| %>
            <tr>
              <th><%= private_shared_location.location.address_type %></th>
              <th><%= private_shared_location.location.address %></th>
              <th><%= private_shared_location.location.lat %></th>
              <th><%= private_shared_location.location.long %></th>
            </tr>
          <% end if @private_locations.present? %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<!-- Page Heading -->
<h1 class="h3 mb-2 text-gray-800">Locations Shared With Me (Public)</h1>
<!-- DataTales Example -->
<div class="card shadow mb-4">
  <div class="card-header py-3">
    <%#= link_to "Add New Location", new_location_path, class: "btn btn-primary" %>
  </div>
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
        <thead>
          <tr>
            <th>Address Type</th>
            <th>Address</th>
            <th>Lat</th>
            <th>Long</th>
          </tr>
        </thead>
        <tfoot>
          <tr>
            <th>Address Type</th>
            <th>Address</th>
            <th>Lat</th>
            <th>Long</th>
          </tr>
        </tfoot>
        <tbody>
          <% @public_locations.each do |public_shared_location| %>
            <tr>
              <th><%= public_shared_location.location.address_type %></th>
              <th><%= public_shared_location.location.address %></th>
              <th><%= public_shared_location.location.lat %></th>
              <th><%= public_shared_location.location.long %></th>
            </tr>
          <% end if @public_locations.present? %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/locations/new.html.erb
<div class="row">
  <!-- <div class="col-lg-5 d-none d-lg-block bg-register-image"></div> -->
  <div class="col-lg-10">
    <div class="p-5">
      <div class="text-center">
        <h1 class="h4 text-gray-900 mb-4">Create a Location</h1>
      </div>
      <!-- <form class="user"> -->
        <%= form_for(@location, class: "user") do |f| %>
          <div class="form-group row">
            <div class="col-sm-6 mb-3 mb-sm-0">
              <!-- <input type="text" class="form-control form-control-user" id="exampleFirstName" placeholder="First Name"> -->
              <%= f.text_field :lat,  class: "form-control form-control-user", id: "latitude", placeholder: "Latitude"%>
            </div>
            <div class="col-sm-6">
              <!-- <input type="text" class="form-control form-control-user" id="exampleLastName" placeholder="Last Name"> -->
              <%= f.text_field :long,  class: "form-control form-control-user", id: "longitude", placeholder: "Longitude"%>
            </div>
          </div>
          <div class="form-group">
            <!-- <input type="email" class="form-control form-control-user" id="exampleInputEmail" placeholder="Email Address"> -->
            <%= f.text_field :address,  class: "form-control form-control-user", id: "address", placeholder: "Address"%>
          </div>
          <div class="form-group">
            <%= f.text_field :address_type,  class: "form-control form-control-user", id: "addressType", placeholder: "Address Type"%>
          </div>
          
          <%= f.submit "Submit", class: "btn btn-primary btn-user btn-block"%>
        <!-- </form> -->
      <% end %>
    </div>
  </div>
</div>

app/views/share_locations/index.html.erb
<!-- Page Heading -->
<h1 class="h3 mb-2 text-gray-800">My Shared Locations</h1>
<!-- DataTales Example -->
<div class="card shadow mb-4">
  <div class="card-header py-3">
    Shared Locations
  </div>
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
        <thead>
          <tr>
            <th>Address Type</th>
            <th>Address</th>
            <th>Lat</th>
            <th>Long</th>
            <th>Shared Type</th>
            <th>Shated With</th>
            <th>Action</th>
          </tr>
        </thead>
        <tfoot>
          <tr>
            <th>Address Type</th>
            <th>Address</th>
            <th>Lat</th>
            <th>Long</th>
            <th>Shared Type</th>
            <th>Shated With</th>
            <th>Action</th>
          </tr>
        </tfoot>
        <tbody>
          <% @shared_locations.each do |shared_location| %>
            <tr>
              <th><%= shared_location.location.address_type %></th>
              <th><%= shared_location.location.address %></th>
              <th><%= shared_location.location.lat %></th>
              <th><%= shared_location.location.long %></th>
              <th><%= shared_location.is_private == 'true' ?  "Private" : "Public"%></th>
              <th><%= shared_location.share_with.try(:name) %></th>
              <th>
                <!-- <a href="#" class="btn btn-danger btn-circle" data-toggle="modal" data-target="#deleteRecordModal">
                  <i class="fas fa-trash"></i>
                </a> -->
                <%= link_to "Delete", share_location_path(shared_location.id), class: "btn btn-danger", method: :delete, :data => { :no_turbolink => true } %>
              </th>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/share_locations/new.html.erb
<div class="row">
  <!-- <div class="col-lg-5 d-none d-lg-block bg-register-image"></div> -->

   <!-- Fade In Utility -->
  <div class="col-lg-10">

    <div class="card position-relative">
      <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Location Type: <%= @location.address_type %></h6>
      </div>
      <div class="card-body">
        <div class="small mb-1">Latitude: <%= @location.lat %></div>
        <div class="small mb-1">Longitudes: <%= @location.long %></div>
        <p class="mb-0 small">Address: <%= @location.address %></p>
      </div>
    </div>

  </div>


  <div class="col-lg-10">
    <div class="p-5">
      <div class="text-center">
        <h1 class="h4 text-gray-900 mb-4">Share Your Location</h1>
      </div>
        <%= form_for(@shared_location, url: location_share_locations_path(@location), class: "shared_location") do |f| %>
          <div class="form-group row">
            <div class="col-sm-6 mb-3 mb-sm-0">
              <%= f.collection_select :share_with_id, User.all.where.not(id: @current_user.id), :id, :name, {}, :multiple => 'true', :class => 'form-control form-control-user' %>
            </div>
            <div class="col-sm-6">
              <%= f.select(:is_private, options_for_select([['Share Privately', true], ['Share Publickly', false]]), :class => 'form-control form-control-user') %>
            </div>
          </div>
          <%= f.submit "Submit", class: "btn btn-primary btn-user btn-block"%>
      <% end %>
    </div>
  </div>
</div>